version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOMAIN: http://127.0.0.1/ ## pastikan selalu menggunakan http:// dan di akhiri dengan tanda / ## jika menggunakan http://localhost/ error
      DBHOST: mysql
      DBNAME: mydatabase
      DBUSER: root
      DBPASS: secret
    ports:
      - 80:80
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
